language: node_js
node_js: node
services: postgresql
before_script: psql -c 'create database palettepicker_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: hshCAyHYExxAvdTsRiY94eDChj8TDvfXJepTffH6/vX3/k3oeS1+KsgXWyF96crunhDyeM3Fhp5pOUGZDN2mnHrY/5QdhEMxwTbq8jq1xmvKDSwFyBF9v4gdzVXBQMvjXCWjdNarcfKrGGGGqtvF98G4Xt/JQAxyxSrsftJGpZ5zCFwUyMcX/9BMOuYWVJMjgrtOtjmiG3yC7ZaIjLx6ekBLcYzNNSdUl7Z3OvG6VbNElwSPPEcxtkFYxMjsws/LihXHxY6vYwv1/rFME4viycGx+Iz1o5oUXDN8mxkBjSpi0Okgcn1uhwbYX4VBIgf/wN6PWYADCqjJS1kiHjdn013+/Q4le7p5uwmyhtCNnFeCDkKhVYbt5OrFxGSf9Eqfjf1fGFKNgRe+knvWQJRgJ9vSKHBQcgHVVsH6xnzdUo4F2gqI2Jo148tNCPEkbAY1YcYyE6d36Zkr06m8pmhX/lvgGvrbQV0DQWPMb/bFII2oQokely7OlrkCnjpxfNoMpwWfPJG40psTgKPdm54OrKDV1h99GPlHOpxvu72JazEDz87m+4x6zlmHdWxQxekat3s2wKwKY6xT7hkRgUOUv1YiZ64ie5ahE4I/mLfe/1LBPqIhHgaAB27CL9P23R1A2ws/ZMUOWLRX4TBRcdJ+2vHT7o5Ox/bCnqvKZ9mLTj0=
  app: palettepickerpat
  